### ISSUE TITLE
What is jest-bdd-generator for?

### ISSUE THREAD

**Issue by tianmagongyue** [tiktok/jest-bdd-generator#6]
What is the relationship between jest-bdd-generator and cucumber? The readme seems to introduce cucumber in a large part.

**Comment by aishiguang** [comment]
Cucumber.js is for Acceptance-Testing. It is unique in many ways such as Context and Steps-Reusing, comparing to Jest.js or any other Unit-test libraries.
This library however is for Unit-Testing, as well as some E2E tests that have similar implementations or design patterns. It completely follows the design patterns of Unit testing, and utilize some of the fancy great ideas that Cucumber has.
